# app/main.py
"""
Main entry point script to run the FaultMaven FastAPI application using Uvicorn.

This script imports the FastAPI 'app' instance from 'app.query_processing'
and starts the Uvicorn ASGI server.

IMPORTANT: To ensure correct module resolution within the 'app' package,
this script MUST be run from the project's ROOT directory using the '-m' flag:
  python -m app.main

Alternatively, use the Uvicorn CLI directly from the root directory:
  uvicorn app.query_processing:app --host 0.0.0.0 --port 8000 --reload (for development)
  uvicorn app.query_processing:app --host 0.0.0.0 --port 8000 --workers 4 (for production)
"""

import uvicorn
import sys
import os
import signal
import logging

# --- Basic Logging Setup ---
# Configures logging for messages generated by this script (e.g., startup/shutdown).
# Uvicorn manages its own request/worker logging based on its config.
logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')

# --- Import the FastAPI app instance ---
# Tries to import the 'app' object defined in app.query_processing.py.
# This relies on running the script correctly with `python -m app.main`.
try:
    from app.query_processing import app
    logging.info("Successfully imported FastAPI app instance from app.query_processing.")
except ImportError as e:
    logging.error(f"ImportError: Failed to import 'app' from 'app.query_processing'. Error: {e}")
    logging.error("--> Please ensure the FastAPI app instance (app = FastAPI()) is defined in 'app/query_processing.py'.")
    logging.error("--> Run this script from the project root directory using: python -m app.main")
    sys.exit(1) # Exit if app cannot be imported
except Exception as e:
    logging.error(f"An unexpected error occurred during app import: {e}")
    sys.exit(1)


# --- Graceful Shutdown Handling ---
def shutdown_handler(signum, frame):
    """Catches termination signals (Ctrl+C, kill) for graceful shutdown."""
    signal_name = signal.Signals(signum).name
    logging.info(f"Received signal {signal_name} ({signum}). Shutting down Uvicorn server...")
    # Uvicorn handles the actual server shutdown process when run programmatically like this.
    # We just need to exit the script cleanly. Add specific cleanup here if needed.
    sys.exit(0)

# Register handlers for common termination signals
signal.signal(signal.SIGINT, shutdown_handler)  # Handles Ctrl+C
signal.signal(signal.SIGTERM, shutdown_handler) # Handles `kill` command or systemd stop


# --- Main Execution Block ---
# This code runs only when the script is executed directly (e.g., `python -m app.main`).
if __name__ == "__main__":
    logging.info("Initializing Uvicorn server...")

    # --- Uvicorn Server Configuration ---
    # Consider moving host, port, workers, reload flags to config/settings.py
    # or environment variables for more flexibility in different environments.
    HOST = "0.0.0.0" # Listen on all available network interfaces
    PORT = 8000      # Standard port for web services
    RELOAD = True    # Enable auto-reload for development (watches for code changes)
                     # SET RELOAD = False for PRODUCTION!
    LOG_LEVEL = "info" # Uvicorn's logging level

    # --- Worker Configuration ---
    # IMPORTANT: Uvicorn's --reload feature works best with only 1 worker process.
    # For production deployments (where reload=False), increase workers
    # (e.g., based on CPU cores: (2 * cpu_cores) + 1 is a common formula).
    WORKERS = 1 if RELOAD else 4

    logging.info(f"Starting server on {HOST}:{PORT}...")
    logging.info(f"Reload mode: {'Enabled' if RELOAD else 'Disabled'}")
    logging.info(f"Number of workers: {WORKERS}")

    # Programmatically run Uvicorn
    uvicorn.run(
        # Target string: 'module:app_instance'
        "app.query_processing:app",
        host=HOST,
        port=PORT,
        workers=WORKERS,
        log_level=LOG_LEVEL,
        reload=RELOAD,
        # reload_dirs=["app", "config"] # Optionally specify directories to watch when reload=True
    )